version: '3.8'

services:
  backend:
    build: /backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:motdepasse@db:5432/monapp
    depends_on:
      - db

  frontend:
    build: /frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: monapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:

